// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: proto/snowflake.proto

package snowflakepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateIDRequest) Reset() {
	*x = GenerateIDRequest{}
	mi := &file_proto_snowflake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIDRequest) ProtoMessage() {}

func (x *GenerateIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snowflake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIDRequest.ProtoReflect.Descriptor instead.
func (*GenerateIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_snowflake_proto_rawDescGZIP(), []int{0}
}

type GenerateIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IdStr         string                 `protobuf:"bytes,2,opt,name=id_str,json=idStr,proto3" json:"id_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateIDResponse) Reset() {
	*x = GenerateIDResponse{}
	mi := &file_proto_snowflake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIDResponse) ProtoMessage() {}

func (x *GenerateIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snowflake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIDResponse.ProtoReflect.Descriptor instead.
func (*GenerateIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_snowflake_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateIDResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GenerateIDResponse) GetIdStr() string {
	if x != nil {
		return x.IdStr
	}
	return ""
}

type ParseIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseIDRequest) Reset() {
	*x = ParseIDRequest{}
	mi := &file_proto_snowflake_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseIDRequest) ProtoMessage() {}

func (x *ParseIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snowflake_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseIDRequest.ProtoReflect.Descriptor instead.
func (*ParseIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_snowflake_proto_rawDescGZIP(), []int{2}
}

func (x *ParseIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ParseIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	TimestampIso  string                 `protobuf:"bytes,3,opt,name=timestamp_iso,json=timestampIso,proto3" json:"timestamp_iso,omitempty"`
	WorkerId      int64                  `protobuf:"varint,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Sequence      int64                  `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseIDResponse) Reset() {
	*x = ParseIDResponse{}
	mi := &file_proto_snowflake_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseIDResponse) ProtoMessage() {}

func (x *ParseIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snowflake_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseIDResponse.ProtoReflect.Descriptor instead.
func (*ParseIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_snowflake_proto_rawDescGZIP(), []int{3}
}

func (x *ParseIDResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ParseIDResponse) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *ParseIDResponse) GetTimestampIso() string {
	if x != nil {
		return x.TimestampIso
	}
	return ""
}

func (x *ParseIDResponse) GetWorkerId() int64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *ParseIDResponse) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type GetServerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerStatusRequest) Reset() {
	*x = GetServerStatusRequest{}
	mi := &file_proto_snowflake_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStatusRequest) ProtoMessage() {}

func (x *GetServerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snowflake_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetServerStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_snowflake_proto_rawDescGZIP(), []int{4}
}

type GetServerStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkerId         int64                  `protobuf:"varint,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CurrentTimestamp int64                  `protobuf:"varint,2,opt,name=current_timestamp,json=currentTimestamp,proto3" json:"current_timestamp,omitempty"`
	Epoch            int64                  `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetServerStatusResponse) Reset() {
	*x = GetServerStatusResponse{}
	mi := &file_proto_snowflake_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStatusResponse) ProtoMessage() {}

func (x *GetServerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snowflake_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStatusResponse.ProtoReflect.Descriptor instead.
func (*GetServerStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_snowflake_proto_rawDescGZIP(), []int{5}
}

func (x *GetServerStatusResponse) GetWorkerId() int64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *GetServerStatusResponse) GetCurrentTimestamp() int64 {
	if x != nil {
		return x.CurrentTimestamp
	}
	return 0
}

func (x *GetServerStatusResponse) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

var File_proto_snowflake_proto protoreflect.FileDescriptor

const file_proto_snowflake_proto_rawDesc = "" +
	"\n" +
	"\x15proto/snowflake.proto\x12\tsnowflake\"\x13\n" +
	"\x11GenerateIDRequest\";\n" +
	"\x12GenerateIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06id_str\x18\x02 \x01(\tR\x05idStr\" \n" +
	"\x0eParseIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xa2\x01\n" +
	"\x0fParseIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12#\n" +
	"\rtimestamp_iso\x18\x03 \x01(\tR\ftimestampIso\x12\x1b\n" +
	"\tworker_id\x18\x04 \x01(\x03R\bworkerId\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\x03R\bsequence\"\x18\n" +
	"\x16GetServerStatusRequest\"y\n" +
	"\x17GetServerStatusResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\x03R\bworkerId\x12+\n" +
	"\x11current_timestamp\x18\x02 \x01(\x03R\x10currentTimestamp\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x03R\x05epoch2\xf9\x01\n" +
	"\x10SnowflakeService\x12I\n" +
	"\n" +
	"GenerateID\x12\x1c.snowflake.GenerateIDRequest\x1a\x1d.snowflake.GenerateIDResponse\x12@\n" +
	"\aParseID\x12\x19.snowflake.ParseIDRequest\x1a\x1a.snowflake.ParseIDResponse\x12X\n" +
	"\x0fGetServerStatus\x12!.snowflake.GetServerStatusRequest\x1a\".snowflake.GetServerStatusResponseB!Z\x1fsnowflake/pkg/proto;snowflakepbb\x06proto3"

var (
	file_proto_snowflake_proto_rawDescOnce sync.Once
	file_proto_snowflake_proto_rawDescData []byte
)

func file_proto_snowflake_proto_rawDescGZIP() []byte {
	file_proto_snowflake_proto_rawDescOnce.Do(func() {
		file_proto_snowflake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_snowflake_proto_rawDesc), len(file_proto_snowflake_proto_rawDesc)))
	})
	return file_proto_snowflake_proto_rawDescData
}

var file_proto_snowflake_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_snowflake_proto_goTypes = []any{
	(*GenerateIDRequest)(nil),       // 0: snowflake.GenerateIDRequest
	(*GenerateIDResponse)(nil),      // 1: snowflake.GenerateIDResponse
	(*ParseIDRequest)(nil),          // 2: snowflake.ParseIDRequest
	(*ParseIDResponse)(nil),         // 3: snowflake.ParseIDResponse
	(*GetServerStatusRequest)(nil),  // 4: snowflake.GetServerStatusRequest
	(*GetServerStatusResponse)(nil), // 5: snowflake.GetServerStatusResponse
}
var file_proto_snowflake_proto_depIdxs = []int32{
	0, // 0: snowflake.SnowflakeService.GenerateID:input_type -> snowflake.GenerateIDRequest
	2, // 1: snowflake.SnowflakeService.ParseID:input_type -> snowflake.ParseIDRequest
	4, // 2: snowflake.SnowflakeService.GetServerStatus:input_type -> snowflake.GetServerStatusRequest
	1, // 3: snowflake.SnowflakeService.GenerateID:output_type -> snowflake.GenerateIDResponse
	3, // 4: snowflake.SnowflakeService.ParseID:output_type -> snowflake.ParseIDResponse
	5, // 5: snowflake.SnowflakeService.GetServerStatus:output_type -> snowflake.GetServerStatusResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_snowflake_proto_init() }
func file_proto_snowflake_proto_init() {
	if File_proto_snowflake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_snowflake_proto_rawDesc), len(file_proto_snowflake_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_snowflake_proto_goTypes,
		DependencyIndexes: file_proto_snowflake_proto_depIdxs,
		MessageInfos:      file_proto_snowflake_proto_msgTypes,
	}.Build()
	File_proto_snowflake_proto = out.File
	file_proto_snowflake_proto_goTypes = nil
	file_proto_snowflake_proto_depIdxs = nil
}
