// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: proto/snowflake.proto

package snowflakepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SnowflakeService_GenerateID_FullMethodName      = "/snowflake.SnowflakeService/GenerateID"
	SnowflakeService_ParseID_FullMethodName         = "/snowflake.SnowflakeService/ParseID"
	SnowflakeService_GetServerStatus_FullMethodName = "/snowflake.SnowflakeService/GetServerStatus"
)

// SnowflakeServiceClient is the client API for SnowflakeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnowflakeServiceClient interface {
	GenerateID(ctx context.Context, in *GenerateIDRequest, opts ...grpc.CallOption) (*GenerateIDResponse, error)
	ParseID(ctx context.Context, in *ParseIDRequest, opts ...grpc.CallOption) (*ParseIDResponse, error)
	GetServerStatus(ctx context.Context, in *GetServerStatusRequest, opts ...grpc.CallOption) (*GetServerStatusResponse, error)
}

type snowflakeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSnowflakeServiceClient(cc grpc.ClientConnInterface) SnowflakeServiceClient {
	return &snowflakeServiceClient{cc}
}

func (c *snowflakeServiceClient) GenerateID(ctx context.Context, in *GenerateIDRequest, opts ...grpc.CallOption) (*GenerateIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateIDResponse)
	err := c.cc.Invoke(ctx, SnowflakeService_GenerateID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snowflakeServiceClient) ParseID(ctx context.Context, in *ParseIDRequest, opts ...grpc.CallOption) (*ParseIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseIDResponse)
	err := c.cc.Invoke(ctx, SnowflakeService_ParseID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snowflakeServiceClient) GetServerStatus(ctx context.Context, in *GetServerStatusRequest, opts ...grpc.CallOption) (*GetServerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerStatusResponse)
	err := c.cc.Invoke(ctx, SnowflakeService_GetServerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnowflakeServiceServer is the server API for SnowflakeService service.
// All implementations must embed UnimplementedSnowflakeServiceServer
// for forward compatibility.
type SnowflakeServiceServer interface {
	GenerateID(context.Context, *GenerateIDRequest) (*GenerateIDResponse, error)
	ParseID(context.Context, *ParseIDRequest) (*ParseIDResponse, error)
	GetServerStatus(context.Context, *GetServerStatusRequest) (*GetServerStatusResponse, error)
	mustEmbedUnimplementedSnowflakeServiceServer()
}

// UnimplementedSnowflakeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnowflakeServiceServer struct{}

func (UnimplementedSnowflakeServiceServer) GenerateID(context.Context, *GenerateIDRequest) (*GenerateIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateID not implemented")
}
func (UnimplementedSnowflakeServiceServer) ParseID(context.Context, *ParseIDRequest) (*ParseIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseID not implemented")
}
func (UnimplementedSnowflakeServiceServer) GetServerStatus(context.Context, *GetServerStatusRequest) (*GetServerStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerStatus not implemented")
}
func (UnimplementedSnowflakeServiceServer) mustEmbedUnimplementedSnowflakeServiceServer() {}
func (UnimplementedSnowflakeServiceServer) testEmbeddedByValue()                          {}

// UnsafeSnowflakeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnowflakeServiceServer will
// result in compilation errors.
type UnsafeSnowflakeServiceServer interface {
	mustEmbedUnimplementedSnowflakeServiceServer()
}

func RegisterSnowflakeServiceServer(s grpc.ServiceRegistrar, srv SnowflakeServiceServer) {
	// If the following call panics, it indicates UnimplementedSnowflakeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnowflakeService_ServiceDesc, srv)
}

func _SnowflakeService_GenerateID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnowflakeServiceServer).GenerateID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnowflakeService_GenerateID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnowflakeServiceServer).GenerateID(ctx, req.(*GenerateIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnowflakeService_ParseID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnowflakeServiceServer).ParseID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnowflakeService_ParseID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnowflakeServiceServer).ParseID(ctx, req.(*ParseIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnowflakeService_GetServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnowflakeServiceServer).GetServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnowflakeService_GetServerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnowflakeServiceServer).GetServerStatus(ctx, req.(*GetServerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnowflakeService_ServiceDesc is the grpc.ServiceDesc for SnowflakeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnowflakeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snowflake.SnowflakeService",
	HandlerType: (*SnowflakeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateID",
			Handler:    _SnowflakeService_GenerateID_Handler,
		},
		{
			MethodName: "ParseID",
			Handler:    _SnowflakeService_ParseID_Handler,
		},
		{
			MethodName: "GetServerStatus",
			Handler:    _SnowflakeService_GetServerStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/snowflake.proto",
}
